spring:
    redis:
        host: 10.10.10.20
        port: 6379
        password:
        lettuce:
            pool:
                min-idle: 0
                max-active: 2
                max-idle: 2


eureka:
    client:
        service-url:
            defaultZone: http://10.10.10.11:8761/eureka,http://10.10.10.12:8761/eureka
    
    