server:
    port: 8081
spring:
    application:
        name: resume-alibaba-service
    
    cloud:
        nacos:
            discovery:
                server-addr: http://localhost:8848
    datasource:
        url: jdbc:mariadb://localhost:3306/springcloud?serverTimezone=GMT%2B8
        username: "root"
        password: "888888"
    
    jpa:
        show-sql: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    