server:
    port: 9001

spring:
    application:
        name: turbine-9001
eureka:
    client:
        service-url:
            default: http://localhost:8761/eureka, http://localhost:8762/eureka
    instance:
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
        prefer-ip-address: true

# Turbine配置
turbine:
    # app-config配置要聚合的微服务名称，多个服务使用英文逗号分隔
    app-config: "Auto Deliver"
    # 集群名称
    cluster-name-expression: "'default'"
