# Eureka Server服务端口
server:
    port: 8762

spring:
    application:
        # 应用名称，应用名称会在Eureka中作为服务名称
        name: Eureka Service

# 配置Eureka客户端（和Server交互），Eureka Server其实也是一个Client
eureka:
    instance:
        # 当前Eureka实例的主机名
        hostname: EurekaService2
        
    client:
        # 配置客户端所交互的Eureka服务端地址
        # Eureka集群中每一个Server其实相对于其它Server来说都是Client
        service-url:
            # 集群模式下，defaultZone应该指向其它Eureka Server，多个Eureka Server使用逗号隔开
            defaultZone: http://EurekaService1:8761/eureka
        # 当前自己就是Server，不需要注册自己
        # 集群模式下为true
        register-with-eureka: true
        # 查询注册中心的服务信息。自己就是Server，所以不需要查询
        # 集群模式下为true
        fetch-registry: true

   