spring:
    profiles:
        active: "8080"

---
server:
    port: 8080

spring:
    profiles: "8080"
    application:
        name: Resume
    datasource:
        url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8
        username: "root"
        password: "888888"
    jpa:
        show-sql: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# 将服务注册到Eureka服务中心当中
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    instance:
        # 服务实例中显示IP，而不显示主机名
        prefer-ip-address: true
        # 自定义实例名称
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
        # 自定义元数据
        metadata-map:
            key1: value1
            key2: value2
logging:
    level:
        org.springframework.web.servlet.DispatcherServlet: debug
        org.springframework.cloud.sleuth: debug
---
server:
    port: 8081
logging:
    level:
        org.springframework.web.servlet.DispatcherServlet: debug
        org.springframework.cloud.sleuth: debug
spring:
    profiles: "8081"
    application:
        name: Resume
    datasource:
        url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8
        username: "root"
        password: "888888"
        driver-class-name: org.mariadb.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    jpa:
        show-sql: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    zipkin:
        base-url: http://localhost:9411
        sender:
            type: web
    
    sleuth:
        sampler:
            probability: 1 # 采样率，代表100%采集，默认：0.1%，生产环境这个值越小越好


# 将服务注册到Eureka服务中心当中
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    instance:
        # 服务实例中显示IP，而不显示主机名
        prefer-ip-address: true
        # 自定义实例名称
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
        # 自定义元数据
        metadata-map:
            key1: value1
            key2: value2
