server:
    port: 9006

spring:
    application:
        name: config-9006
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/AyStyle/MySpringCloudRoadOfGrowth.git # 配置Git服务地址
                    username: dreedisgood@qq.com        # 配置Git账号
                    password: An94Fation100%               # 配置Git密码
                    default-label: master # Git远程分支配置
                    search-paths:
                        - MySpringCloudRoadOfGrowth
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
eureka:
    instance:
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
        prefer-ip-address: true
    client:
        service-url:
            default: http://localhost:8761/eureka,http://localhost:8761/eureka
            
            
# 健康检查
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always