server:
    port: 9006

spring:
    application:
        name: config-9006
    cloud:
        config:
            server:
                git:
                    uri: https://gitee.com/xiaoyaoay/first_stage_module_i.git # 配置Git服务地址
                    username: dreedisgood@qq.com         # 配置Git账号
                    password: An94aiYi100%               # 配置Git密码
                    search-paths:
                        - first_stage_module_i
                label: master # Git远程分支配置
eureka:
    instance:
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
        prefer-ip-address: true
    client:
        service-url:
            default: http://localhost:8761/eureka,http://localhost:8761/eureka
# 健康检查
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always