# Eureka Server服务端口
server:
    port: 8761

spring:
    application:
        # 应用名称，应用名称会在Eureka中作为服务名称
        name: Eureka Service

# 配置Eureka客户端（和Server交互），Eureka Server其实也是一个Client
eureka:
    instance:
        # 当前Eureka实例的主机名
        hostname: EurekaService1
        
    client:
        # 配置客户端所交互的Eureka服务端地址
        service-url:
            defaultZone: http://EurekaService2:8762/eureka
        # 当前自己就是Server，不需要注册自己
        register-with-eureka: true
        # 查询注册中心的服务信息。自己就是Server，所以不需要查询
        fetch-registry: true

   