server:
    port: 9999

spring:
    application:
        name: oauth2-server
    datasource:
        url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8
        username: "root"
        password: "888888"
        driver-class-name: org.mariadb.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    
    jpa:
        show-sql: true
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:@project.version@
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka