server:
    port: 9999

spring:
    application:
        name: oauth2-server

eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:@project.version@
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka