eureka:
    instance:
        prefer-ip-address: false
    client:
        service-url:
            defaultZone: http://EurekaService1:8671/ereuka,http://EurekaService1:8671/ereuka
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mariadb://MariaDB:6033/springcloud?serverTimezone=GMT%2B8
        username: root
        password: 888888
        driver-class-name: org.mariadb.jdbc.Driver